config/routes.rb
require 'recaptcha/configuration'

  ReCAPTCHAExample::Application.routes.draw do
      resource :home, only: [:show], controller: :home
        resource  :users, only: [:new, :create]
          root to: "home#show"
  end
  

app/models/statement.rb
class Statement < ActiveRecord::Base


  def initialize(customer)
    @customer = customer
  end

  def generate
    "Statement for #{@customer.name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, on: :create
  validates :email, uniqueness: true, presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base



end


  #YT_LINK_FORMAT = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  #
  #before_create -> do
  #  self.uid = link.match(YT_LINK_FORMAT)
  #
  #self.uid = uid[2] if uid && uid[2]
  #
  #  if self.uid.to_s.length != 11
  #    self.errors.add(:link, 'is invalid.')
  #    false
  #  elsif Video.where(uid: self.uid).any?
  #    self.errors.add(:link, 'is not unique.')
  #    false
  #  else
  #    get_additional_info
  #  end
  #end
  #
  #validates :link, presence: true

  #request = "URL: https://www.googleapis.com/youtube/v3/videos?id=7lCDEYXw3mM&key=AIzaSyAh0CZ-jWpREV-3WtQ-4thTW0T-qU6_zrc
  #  &part=snippet,contentDetails,statistics,status"

  #request = "URL: https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=30&q=agile+ventures+scrums&type=video&key=AIzaSyAh0CZ-jWpREV-3WtQ-4thTW0T-qU6_zrc"


      #request = "http://gdata.youtube.com/feeds/api/users/#{user_id}/uploads?alt=json&max-results=50"
      #request += '&fields=entry(author(name),id,published,title,content,link)'

      #tags_filter = escape_query_params(tags)
      #request += '&q=' + tags_filter.join('|')






  #def get_additional_info
  #  begin
  #    client = YouTubeIt::Client.new(dev_key: ENV['AIzaSyAh0CZ-jWpREV-3WtQ-4thTW0T-qU6_zrc'])
  #    request = 'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=30'
  #    request += '&q=agile+ventures+scrums&type=video'
  #    count = videos.total_result_count


#      client = YouTubeIt::Client.new(:dev_key => "dev_key_supplied_by_youtube_after_you_register_for_their_api")
#      videos = client.videos_by(:user => "some persons youtube username)
#  count = videos.total_result_count
#Then in view
#
#  <%= "So and so has <%= count %> videos on youtube" %>



      #https://gdata.youtube.com/feeds/api/videos?
      #q=football+-soccer
      #&orderby=published
      #&start-index=11
      #&max-results=10
      #&v=2
      #
      #request = 'http://gdata.youtube.com/feeds/api/videos?alt=json&max-results=50'
      #request += '&orderby=published'
      #request += '&fields=entry(author(name),id,published,title,content,link)'
      ##request += '&fields=entry[' + filter.join(' or ') + ']'
      #request += '&q=(' + project_tags_filter.join('|') + ')'
      #request += '/(' + members_filter.join('|') + ')'

      #video = client.video_by(:title => "Agile Ventures")
    #  self.title = video.title
    #  self.duration = parse_duration(video.duration)
    #  self.author = video.author.name
    #  self.likes = video.rating.likes
    #  self.dislikes = video.rating.dislikes
    #rescue
    #  self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = 0 ; self.dislikes = 0

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
        @user = User.new
  end

    def create
          captcha_message = "The data you entered for the CAPTCHA wasn't correct.  Please try again"
            @user = User.new(user_params)
                  if !verify_recaptcha(model: @user, message: captcha_message) || !@user.save
                          render "new"
                  end
    end

    private
      def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
              end
      end

app/controllers/videos_controller.rb
class VideosController < ActionController::Base


  def index
    @videos = Video.all


      #@scrums = Scrum.all

      client = YouTubeIt::Client.new(:dev_key => "AIzaSyAh0CZ-jWpREV-3WtQ-4thTW0T-qU6_zrc")
      query = client.videos_by(:query => "agile ventures scrums")
      @videos = query.videos.map(&:video_id).map{ |str| str.scan(/tag:youtube.com,\d+:video:(.+)/).last.first}

  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(params[:video])
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to root_url
    else
      render 'new'
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def video_link(video)
    link_to video, video['url'], id: video, class: 'yt_link', data: { content: video['content']}
  end

  def video_embed_link(video)
    "http://www.youtube.com/embed/#{video['id']}?enablejsapi=1"
  end



end

#def video_link(video)
#  link_to video[:title], video[:url], id: video[:id], class: 'yt_link', data: { content: video[:content] }
#end
#
#def video_embed_link(video)
#  "http://www.youtube.com/embed/#{video[:id]}?enablejsapi=1"
#end

app/views/home/show.html.erb
<h3>Welcome!</h3>
<p>
click the link below to sign up for an account.
</p>
<%= link_to "Sign Up!", new_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SitepointYtVideos</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="https://www.google.com/jsapi" type="text/javascript"></script>
  <script src="https://www.youtube.com/iframe_api"></script>



</head>
<body>

<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= value %>
      </div>
  <% end %>
</div>

<%= yield %>

<div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="http://radiant-wind.com" target="_blank">Radiant Wind</a></p>
  </div>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">The following errors were found while submitting the form:</h3>
      </div>

      <div class="panel-body">
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/users/create.html.erb
<h3>thank You!</h3>
<p>
  Thanks for signing up!
</p>

app/views/users/new.html.erb
<h3>New User Sign Up</h3>
<% if !@user.errors.empty? %>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for User.new do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div>
            <%= recaptcha_tags %>
          </div>
          <div>
              <%= f.submit "Sign Up" %>
            </div>
          <% end %>

app/views/videos/index.html.erb
<%= javascript_include_tag 'videos' %>


<div class="jumbotron">
  <div class="container">
    <h1>Welcome to the Scrums Page</h1>
    <p>Choose a Scrum to view.</p>
    <p>
      <%= link_to 'List of scrums!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>


<div class="row">
  <div class="col-md-7 col-sm-7">
    <td><h4 id="video_contents"><%= @videos.first['content'] %></h4></td>
    <iframe id="ytplayer" type="text/html" width="250" height="250" src="//www.youtube.com/embed/<%= @videos.last %>" frameborder="0"></iframe>
  </div>
  <div class="col-md-5 col-sm-5">
    <h4>Programming sessions</h4>
    <table class="table table-bordered table-striped table-hover table-condensed">
      <% @videos.each do |video| %>
          <tr>
            <td><%= video_link(video) %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>

  <%= form_for @video do |f| %>
      <%= render 'shared/errors', object: @video %>

      <div class="form-group">
        <%= f.label :link %>
        <%= f.text_field :link, class: 'form-control', required: true %>
        <span class="help-block">A link to the video on YouTube.</span>
      </div>

      <%= f.submit class: 'btn btn-default' %>
  <% end %>
</div>